test

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -24,7 +24,7 @@ jobs:
       uses: actions/upload-artifact@v2
       with:
         name: builded_app
-        path: dist/
+        path: dist
     - name: Testing your code
       run: npm run test
 
@@ -37,7 +37,8 @@ jobs:
         with:
           name: builded_app
       - shell: bash
-        run: "[ -d \"dist\" ] && echo \"Artifacts exists.\" || echo \"Error: Artifacts does not exists.\""
+        # run: "[ -d \"dist\" ] && echo \"Artifacts exists.\" || echo \"Error: Artifacts does not exists.\""
+        run: ls
       - name: Mark current main as new version of app
         run: echo Set new tag in main branch
       - name: Download builded_app to server and run
